default_install_hook_types:
  - pre-commit
  - commit-msg

#TODO - ignore ROOT roles for now
exclude: |
  (?x)^(
    ansible/roles/.*
  )

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: |
          (?x)^(
            \.gitlab-ci\.yml |
            ci/.*\.yml
          )$
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: no-commit-to-branch
        args: [--pattern, '^(release)\/[a-z0-9._-]+$']

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.2
    hooks:
      - id: check-gitlab-ci
        files: |
          (?x)^(
            \.gitlab-ci\.yml |
            ci/.*
          )$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_tflint
        args:
          - --args=--no-color
      - id: terraform_fmt
        args:
          - --args=-recursive
          - --args=-no-color
      - id: terraform_validate
        exclude: \.terraform\.lock\.hcl$
        args:
          - --hook-config=--parallelism-ci-cpu-cores=1
          - --hook-config=--retry-once-with-cleanup=true
          - --tf-init-args=-backend=false
          - --args=-no-color
      - id: terraform_trivy
        files: ^terraform/
        args:
          - --args=--skip-dirs="**/.terraform"
          - --args=--skip-dirs="./.just"
          - --args=--tf-exclude-downloaded-modules

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/anderseknert/pre-commit-opa
    rev: 8b72c4a
    hooks:
      - id: conftest-fmt

  - repo: https://github.com/StyraInc/regal
    rev: v0.34.1
    hooks:
      - id: regal-lint

