name: Linting Checks Ansible

on:
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ansible-lint
        # Official Ansible lint GitHub Action
        uses: ansible/ansible-lint-action@v6
        with:
          # Optional: specify where your playbooks/roles live
          path: ./ansible
