name: Slack Notification

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      step:
        required: true
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C097G9TNLA1'
          payload: |
            {
              "text": "${{ inputs.step }} step ${{ inputs.status == 'success' && 'succeeded' || 'failed' }}.",
              "attachments": [
                {
                  "color": "${{ inputs.status == 'success' && '#2eb886' || '#e01e5a' }}",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": ":${{ inputs.status == 'success' && 'white_check_mark' || 'x' }}: *Terraform ${{ inputs.step }} ${{ inputs.status }}!*"
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        { "type": "mrkdwn", "text": "*Repository:*\n`${{ github.repository }}`" },
                        { "type": "mrkdwn", "text": "*Branch:*\n`${{ github.head_ref || github.ref_name }}`" },
                        { "type": "mrkdwn", "text": "*Commit:*\n`${{ github.sha }}`" },
                        { "type": "mrkdwn", "text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View>" }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

