name: Terraform Validate

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Slack Notification on Validation Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C097G9TNLA1' # Replace with your Slack channel ID
          payload: |
            {
              "text": "Terraform Validation Failed!",
              "attachments": [ { "color": "#e01e5a", "blocks": [
                  { "type": "section", "text": { "type": "mrkdwn", "text": ":warning: *Terraform Validation Failed!*" }},
                  { "type": "section", "fields": [
                      { "type": "mrkdwn", "text": "*Repository:*\n`${{ github.repository }}`" },
                      { "type": "mrkdwn", "text": "*Branch:*\n`${{ github.head_ref || github.ref_name }}`" },
                      { "type": "mrkdwn", "text": "*Commit:*\n`${{ github.sha }}`" },
                      { "type": "mrkdwn", "text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View>" }
                    ]
                  }
              ] } ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
